[tools]
gh = "latest"
node = "latest"
bats = "latest"
black = "latest"
pi = "latest"
ruff = "latest"
shellcheck = "latest"
shfmt = "latest"
"aqua:firecracker-microvm/firecracker" = "latest"
lima = "latest"
microsandbox = "latest"
uv = "latest"
python = "latest"
